-- Postgres (Supabase) version of app/db.py's SCHEMA.
--
-- The app runs this automatically on startup (every statement is
-- IF NOT EXISTS, so it's safe to re-run). You can also paste it into
-- Supabase's SQL Editor by hand if you'd rather create the tables yourself.
--
-- Differences from the SQLite schema:
--   * BIGINT everywhere SQLite had INTEGER: Telegram chat/user/update ids
--     (e.g. channel ids like -1004380334167) don't fit in a 32-bit int.
--   * Timestamps stay TEXT (ISO 8601, "...Z") so the app code that parses
--     and sorts them works identically on both backends.
--   * note_groups is created before notes, since Postgres checks the
--     foreign key target exists at CREATE time.
--   * Row Level Security is enabled on every table with NO policies. The
--     app connects as the database owner (which bypasses RLS), while
--     Supabase's public REST API (anon / authenticated keys) can read or
--     write nothing - these tables hold private notes and drafts.

CREATE TABLE IF NOT EXISTS note_groups (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rationale   TEXT NOT NULL,
    created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS notes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source          TEXT NOT NULL CHECK (source IN ('telegram', 'import')),
    type            TEXT NOT NULL CHECK (type IN ('text', 'voice')),
    tg_message_id   BIGINT,
    raw_text        TEXT,
    audio_path      TEXT,
    transcript      TEXT,
    clean_text      TEXT,
    tags            TEXT,
    piece_type      TEXT,
    group_id        BIGINT REFERENCES note_groups(id),
    status          TEXT NOT NULL DEFAULT 'new'
                        CHECK (status IN ('new', 'shortlisted', 'used', 'parked')),
    park_reason     TEXT,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS batches (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at  TEXT NOT NULL,
    finished_at TEXT,
    status      TEXT NOT NULL DEFAULT 'running'
                    CHECK (status IN ('running', 'sent', 'skipped', 'failed')),
    skipped     BIGINT NOT NULL DEFAULT 0,
    message_id  BIGINT
);

CREATE TABLE IF NOT EXISTS scores (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id     BIGINT NOT NULL REFERENCES notes(id),
    batch_id    BIGINT NOT NULL REFERENCES batches(id),
    score       BIGINT NOT NULL CHECK (score BETWEEN 0 AND 10),
    reason      TEXT NOT NULL,
    model       TEXT NOT NULL,
    created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS picks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id    BIGINT NOT NULL REFERENCES batches(id),
    note_id     BIGINT NOT NULL REFERENCES notes(id),
    picked_at   TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS news_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id         BIGINT NOT NULL REFERENCES notes(id),
    title           TEXT NOT NULL,
    source          TEXT,
    published_at    TEXT,
    link            TEXT NOT NULL,
    fetched_at      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS drafts (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id                 BIGINT NOT NULL REFERENCES notes(id),
    pick_id                 BIGINT REFERENCES picks(id),
    version                 BIGINT NOT NULL DEFAULT 0,
    parent_draft_id         BIGINT REFERENCES drafts(id),
    text                    TEXT NOT NULL,
    news_item_id            BIGINT REFERENCES news_items(id),
    verify_count            BIGINT NOT NULL DEFAULT 0,
    word_count              BIGINT NOT NULL,
    selfcheck_notes         TEXT,
    lint_warnings           TEXT,
    revision_instruction    TEXT,
    created_at              TEXT NOT NULL,
    sent_at                 TEXT
);

CREATE TABLE IF NOT EXISTS decisions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id    BIGINT NOT NULL REFERENCES drafts(id),
    action      TEXT NOT NULL CHECK (action IN ('approve', 'revise', 'reject')),
    reason      TEXT,
    decided_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pending_input (
    chat_id     BIGINT PRIMARY KEY,
    draft_id    BIGINT NOT NULL REFERENCES drafts(id),
    kind        TEXT NOT NULL CHECK (kind IN ('revise', 'reject_reason')),
    created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts          TEXT NOT NULL,
    level       TEXT NOT NULL,
    component   TEXT NOT NULL,
    event       TEXT NOT NULL,
    detail      TEXT
);

CREATE TABLE IF NOT EXISTS processed_updates (
    update_id       BIGINT PRIMARY KEY,
    processed_at    TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_notes_status ON notes(status);
CREATE INDEX IF NOT EXISTS idx_scores_note ON scores(note_id);
CREATE INDEX IF NOT EXISTS idx_drafts_note ON drafts(note_id);
CREATE INDEX IF NOT EXISTS idx_decisions_draft ON decisions(draft_id);

ALTER TABLE note_groups       ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes             ENABLE ROW LEVEL SECURITY;
ALTER TABLE batches           ENABLE ROW LEVEL SECURITY;
ALTER TABLE scores            ENABLE ROW LEVEL SECURITY;
ALTER TABLE picks             ENABLE ROW LEVEL SECURITY;
ALTER TABLE news_items        ENABLE ROW LEVEL SECURITY;
ALTER TABLE drafts            ENABLE ROW LEVEL SECURITY;
ALTER TABLE decisions         ENABLE ROW LEVEL SECURITY;
ALTER TABLE pending_input     ENABLE ROW LEVEL SECURITY;
ALTER TABLE logs              ENABLE ROW LEVEL SECURITY;
ALTER TABLE processed_updates ENABLE ROW LEVEL SECURITY;
